### ISSUE TITLE
Other comuters

### ISSUE THREAD

**Issue by Oddball1987** [dominickfau/FishbowlLabelGenerator#1]
We are having the same issues as before trying to open label generator on another computer. We have tried both the 32 and 64 option and both will open the black CMD screen and then flash of white screen and disappear. Both work on my computer though
[program_log.log](https://github.com/dominickfau/FishbowlLabelGenerator/files/7678092/program_log.log)
[program_log.log](https://github.com/dominickfau/FishbowlLabelGenerator/files/7678094/program_log.log)
.

**Comment by dominickfau** [comment]
Navigate to the application executable location via file explorer. Then in the folder location field (right next to the search bar) type cmd then press enter. Within the command prompt, enter the application executable name make sure to include the .exe at the end, then press enter. Take a screenshot of this the add it here.

**Comment by dominickfau** [comment]
I have fixed the issue in [this commit.](https://github.com/dominickfau/FishbowlLabelGenerator/commit/0c23e00d5e3cf2cdb35d16919568dd995b1f780f)
Download [V1.0.0](https://github.com/dominickfau/FishbowlLabelGenerator/releases/tag/V1.0.0) and try again.

**Comment by Oddball1987** [comment]
have downloaded both files and neither work on another computer. Have went through the steps listed above and ger (is not recognized) error.

**Comment by Oddball1987** [comment]
yes. I have both in the fishbowl folder

**Comment by Oddball1987** [comment]
Have tried this again. Neither 32 or 64 work on any other computer. Loads black screen and then closes.

**Comment by Oddball1987** [comment]
Microsoft Windows [Version 10.0.19042.1288]

(c) Microsoft Corporation. All rights reserved.

 

P:\Fishbowl\ADMIN\FishbowlLabelGenerator>FishbowlLabelGenerator.exe

[root] 2021-12-10 09:36:35 [INFO] in FishbowlLabelGenerator: ==================================================

[root] 2021-12-10 09:36:35 [INFO] in FishbowlLabelGenerator: Starting application... Version: 1.0.0

[root] 2021-12-10 09:36:35 [INFO] in FishbowlLabelGenerator: Windows OS detected. Version: "10.0.19041" Architecture: [Bits: "32bit", Linkage: "WindowsPE"]

[root] 2021-12-10 09:36:36 [ERROR] in FishbowlLabelGenerator: Application failed to start.

[root] 2021-12-10 09:36:36 [ERROR] in FishbowlLabelGenerator: Exception: (-2147221005, 'Invalid class string', None, None)

Traceback (most recent call last):

  File "win32com\client\dynamic.py", line 86, in _GetGoodDispatch

pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "FishbowlLabelGenerator.py", line 466, in <module>

  File "FishbowlLabelGenerator.py", line 454, in main

  File "FishbowlLabelGenerator.py", line 153, in __init__

  File "FishbowlLabelGenerator.py", line 80, in __init__

  File "win32com\client\__init__.py", line 117, in Dispatch

  File "win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName

  File "win32com\client\dynamic.py", line 88, in _GetGoodDispatch

pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

Traceback (most recent call last):

  File "win32com\client\dynamic.py", line 86, in _GetGoodDispatch

pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "FishbowlLabelGenerator.py", line 470, in <module>

  File "FishbowlLabelGenerator.py", line 466, in <module>

  File "FishbowlLabelGenerator.py", line 454, in main

  File "FishbowlLabelGenerator.py", line 153, in __init__

  File "FishbowlLabelGenerator.py", line 80, in __init__

  File "win32com\client\__init__.py", line 117, in Dispatch

  File "win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName

  File "win32com\client\dynamic.py", line 88, in _GetGoodDispatch

pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

[1592] Failed to execute script 'FishbowlLabelGenerator' due to unhandled exception!

 

P:\Fishbowl\ADMIN\FishbowlLabelGenerator>

**Comment by dominickfau** [comment]
Try installing "Dymo Software\DLS8Setup.8.7.exe".

**Comment by Oddball1987** [comment]
All was working well until this afternoon. I can print stickers individually but if i click print all the program crashes and closes. I am not getting anything on the program log but if i run it with python i get "Process finished with exit code -1073740791 (0xC0000409)"

**Comment by dominickfau** [comment]
Could you attach the program logs? I will need both inside the Logs folder. DONT COPY AND PASTE the contents.

**Comment by Oddball1987** [comment]
[program_log.log](https://github.com/dominickfau/FishbowlLabelGenerator/files/7745616/program_log.log)

**Comment by Oddball1987** [comment]
64 bit does the same thing, unable to press the print all button

**Comment by Oddball1987** [comment]
[backend.log](https://github.com/dominickfau/FishbowlLabelGenerator/files/7762912/backend.log)
[frontend.log](https://github.com/dominickfau/FishbowlLabelGenerator/files/7762913/frontend.log)

**Comment by dominickfau** [comment]
I have removed the print all button. Now select what rows to print and they will be removed from the list. There is a setting in the registry to disable this. Also I have added a limit to how many labels can be printed at a time. All settings can be found under 'Computer\HKEY_CURRENT_USER\SOFTWARE\DF-Software\Fishbowl Label Generator'.
Log file have moved to the Documents\DF-Software\Fishbowl Label Generator.

**Comment by Oddball1987** [comment]
I can get to the software but cant fin the DF-software. The print all button is still there on both the 64 and 32 version. I have deleted and reinstalled all programs but didn't help at all. I have selected the line I want to print and it prints fine but doesn't delete that line.

**Comment by dominickfau** [comment]
I just downloaded the current release, and it worked. Showing version 1.0.6 in the window title.

**Comment by Oddball1987** [comment]
I have received my new label printer but can not seem to figure out how to get it to select that printer for labels. I have tried preferences and change printer but nothing shows up. The computer does show the printer available though.
